Feature/bills issues
welaborate-labs/inka_backoffice pull request #63
Opened 2022-11-07 14:16 UTC by rodolforpr88

Refactor some issues in the bills

add `status` field for the `bill`
add the validation `duplicated` to avoid duplicated calls if bill is billing or billed
refactor the test for `bill_spec`

2022-11-07 15:31 UTC, filabreu requested changes

2022-11-07 15:31 UTC, filabreu commented on app/models/bill.rb
> +    return unless Bill.billing_or_billed.includes(:bookings).pluck('bookings.id').reject(&:nil?).any? do |booking_id|
:+1:

2022-11-07 15:31 UTC, filabreu commented on app/views/bookings/in_progress.html.erb
> +  <%= link_to "Voltar para Clientes" , customers_path, class: "button is-link" %>
You can remove the extra space before the comma

2022-11-07 15:31 UTC, filabreu commented on app/views/bookings/in_progress.html.erb
> +    <%= form.label "Aplicar desconto" , class: "label mr-2" %>
You can remove the extra space before the comma

2022-11-07 15:31 UTC, filabreu commented on spec/models/bill_spec.rb
> +  # end
Let's make this mock work!

2022-11-07 17:05 UTC, rodolforpr88 commented on app/views/bookings/in_progress.html.erb
> +  <%= link_to "Voltar para Clientes" , customers_path, class: "button is-link" %>
Removed.

2022-11-07 17:06 UTC, rodolforpr88 commented on app/views/bookings/in_progress.html.erb
> +    <%= form.label "Aplicar desconto" , class: "label mr-2" %>
Removed.

2022-11-10 15:26 UTC, filabreu approved these changes

2022-11-10 15:26 UTC, merged